version: '3'

services:
  mysqldb:
    restart: always
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_DATABASE: weather_station
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql

    ports:
      - "6033:3306"
     
  spring-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysqldb
